# Generated by Django 3.2.13 on 2022-05-21 15:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('free_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'ordering': ['-created_at'],
            },
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Questionnaire',
                'ordering': ['-created_at'],
            },
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('seq_no', models.PositiveSmallIntegerField(default=1)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Short Answer'), (1, 'Paragraph'), (2, 'Checkboxes'), (3, 'Multiple Choice'), (4, 'Dropdown')])),
                ('choice_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['seq_no'],
            },
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
