# Generated by Django 3.2.13 on 2022-05-24 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.questions'),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=models.Index(fields=['title', 'seq_no'], name='quiz_questi_title_558ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaireresponses',
            index=models.Index(fields=['pin'], name='quiz_questi_pin_2ec17e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['title'], name='quiz_questi_title_c41a94_idx'),
        ),
    ]
