# Generated by Django 3.2.13 on 2022-05-23 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='start_date',
        ),
        migrations.CreateModel(
            name='QuestionnaireUserAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.PositiveSmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('answered_by', models.EmailField(max_length=255)),
                ('answers', models.ManyToManyField(blank=True, related_name='questionnaire_user_answers', to='quiz.Answers')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user_answers', to='quiz.questionnaire')),
            ],
            options={
                'verbose_name_plural': 'Questionnaire User Answers',
                'ordering': ['-created_at'],
            },
            managers=[
                ('filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
