# Generated by Django 3.2.13 on 2022-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220523_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireuseranswers',
            name='answered_by',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
